# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-07 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NEO', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neoaddress',
            options={'ordering': ['-create_time'], 'verbose_name': 'NEO地址表'},
        ),
        migrations.AlterModelOptions(
            name='neoblockinfo',
            options={'ordering': ['-create_time'], 'verbose_name': 'NEO区块已校验表'},
        ),
        migrations.AlterModelOptions(
            name='neotransactions',
            options={'ordering': ['-create_time'], 'verbose_name': 'NEO交易记录表'},
        ),
        migrations.AlterModelTable(
            name='neoaddress',
            table='neoaddress',
        ),
        migrations.AlterModelTable(
            name='neoblockinfo',
            table='neoblockinfo',
        ),
        migrations.AlterModelTable(
            name='neotransactions',
            table='neotransactions',
        ),
    ]
