# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEO', '0002_auto_20180807_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCAddress',
            fields=[
                ('id', models.AutoField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('CoinCode', models.CharField(blank=True, help_text='币种', max_length=128, verbose_name='币种')),
                ('Myaddress', models.CharField(blank=True, default='', help_text='地址', max_length=256, verbose_name='地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('IsDelete', models.BooleanField(default='', help_text='是否删除', verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSystem',
            fields=[
                ('id', models.AutoField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('CoinCode', models.CharField(blank=True, help_text='币种类型', max_length=128, verbose_name='币种类型')),
            ],
            options={
                'verbose_name': '业务系统表',
                'db_table': 'business_system',
            },
        ),
        migrations.CreateModel(
            name='ETHAddress',
            fields=[
                ('id', models.AutoField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('CoinCode', models.CharField(blank=True, help_text='币种', max_length=128, verbose_name='币种')),
                ('Myaddress', models.CharField(blank=True, default='', help_text='地址', max_length=256, verbose_name='地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('IsDelete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
            ],
            options={
                'verbose_name': 'ETH地址表',
                'db_table': 'ethaddress',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ETHAddressBusinessSystem',
            fields=[
                ('id', models.AutoField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('IsDelete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('IsUse', models.BooleanField(default=False, help_text='是否使用', verbose_name='是否使用')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('BusinessSystem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEO.BusinessSystem', verbose_name='业务系统')),
                ('CoinAddr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NEO.ETHAddress', verbose_name='币种地址')),
            ],
            options={
                'verbose_name': 'ETH地址与业务系统表',
                'db_table': 'eth_address_business_system',
            },
        ),
        migrations.DeleteModel(
            name='NEOAddress',
        ),
        migrations.DeleteModel(
            name='NEOBlockInfo',
        ),
        migrations.DeleteModel(
            name='NEOTransactions',
        ),
    ]
