# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-08 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEO', '0003_auto_20180808_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_task',
            fields=[
                ('id', models.AutoField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, help_text='任务名称', max_length=128, verbose_name='任务名称')),
                ('coin_name', models.CharField(blank=True, help_text='币种', max_length=128, verbose_name='币种')),
                ('coin_num', models.IntegerField(blank=True, help_text='数量', max_length=128, null=True, verbose_name='数量')),
                ('is_finish', models.BooleanField(default=False, help_text='是否完成', verbose_name='是否完成')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default='', help_text='是否删除', verbose_name='是否删除')),
            ],
        ),
    ]
