# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-08 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEO', '0004_create_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_task',
            name='coin_num',
            field=models.IntegerField(blank=True, help_text='数量', null=True, verbose_name='数量'),
        ),
    ]
