# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEO', '0006_otheraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherAddressBusinessSystem',
            fields=[
                ('id', models.AutoField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('CoinAddr_id', models.IntegerField(blank=True, default=False, help_text='币种', verbose_name='币种')),
                ('BusinessSystem_id', models.IntegerField(blank=True, default=False, help_text='系统信息', verbose_name='系统信息')),
                ('IsDelete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('IsUse', models.BooleanField(default=False, help_text='是否使用', verbose_name='是否使用')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
            ],
            options={
                'verbose_name': 'Other地址与业务系统表',
                'db_table': 'other_address_business_system',
            },
        ),
        migrations.DeleteModel(
            name='BTCAddress',
        ),
        migrations.RemoveField(
            model_name='ethaddressbusinesssystem',
            name='BusinessSystem_id',
        ),
        migrations.RemoveField(
            model_name='ethaddressbusinesssystem',
            name='CoinAddr_id',
        ),
        migrations.AlterModelOptions(
            name='create_task',
            options={'ordering': ['-create_time'], 'verbose_name': '任务生成表'},
        ),
        migrations.AlterModelOptions(
            name='otheraddress',
            options={'verbose_name': 'Other地址表'},
        ),
        migrations.AlterModelTable(
            name='create_task',
            table='create_task',
        ),
        migrations.DeleteModel(
            name='BusinessSystem',
        ),
        migrations.DeleteModel(
            name='ETHAddress',
        ),
        migrations.DeleteModel(
            name='ETHAddressBusinessSystem',
        ),
    ]
