# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-10 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEO', '0007_auto_20180809_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEOAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.CharField(max_length=256, verbose_name='币种类型')),
                ('address', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_use', models.BooleanField(default=False, verbose_name='是否使用')),
            ],
            options={
                'verbose_name': 'neo地址表',
                'db_table': 'neo_address',
            },
        ),
        migrations.CreateModel(
            name='NEOAddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.CharField(default='NEO', max_length=128, verbose_name='币种类型')),
                ('asset', models.CharField(max_length=256, verbose_name='资产类型')),
                ('block_index', models.IntegerField(default=True, verbose_name='区块索引')),
                ('tx_id', models.CharField(max_length=256, verbose_name='交易标示')),
                ('create_time', models.DateTimeField(default=True, verbose_name='交易创建时间')),
                ('address', models.CharField(max_length=256, verbose_name='地址')),
                ('category', models.BooleanField(verbose_name='转入转出')),
                ('amount', models.BigIntegerField(verbose_name='转入转出金额')),
            ],
            options={
                'verbose_name': 'neo地址表',
                'db_table': 'neo_address_info',
            },
        ),
        migrations.DeleteModel(
            name='Create_task',
        ),
        migrations.DeleteModel(
            name='OtherAddress',
        ),
        migrations.AlterField(
            model_name='otheraddressbusinesssystem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
